#! /bin/sh

xmodmap -e "pointer = 3 2 1"
feh --bg-fill ~/Nextcloud/Pictures/Wallpapers/chi_train_blurturn.jpg
xss-lock -- i3lock-fancy -p -- scrot -z &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a telegram-desktop desktop='^2'

sxhkd &
tint2 &
mate-volume-control-status-icon &
nm-applet &
nextcloud &
telegram-desktop &
