#! /bin/sh

# force bash for BSPWM
#set -U SXHKD_SHELL /usr/bin/bash

# switch left and right mouse buttons
xmodmap -e "pointer = 3 2 1"

# set wallpaper and lock screen
feh --bg-fill ~/Pictures/car_nascar_jj.jpg
xss-lock -- i3lock-fancy -p -- scrot -z &

# load cursor theme
xsetroot -cursor_name left_ptr

#/home/liam/display-scripts/all.sh

# set monitors and desktops
bspc monitor DVI-D-0 -d L1 L2 L3
bspc monitor DP-0 -d C1 C2 C3 C4
bspc monitor DP-2 -d R1 R2 R3

# configuration
bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.66
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam desktop=^7

# starup programs
sxhkd &
#tint2 &
mate-volume-control-status-icon &
nm-applet &
wmname LG3D & # fix android studio
steam &
gtk-launch vivaldi-adpgfoaiaohhedbfjfajiaeniofgjlfk-Default.desktop && sleep 2 && bspc node -d '^1' & # telegram chrome app
