#! /bin/sh

# force bash for BSPWM
#set -U SXHKD_SHELL /usr/bin/bash

# switch left and right mouse buttons
xmodmap -e "pointer = 3 2 1"

# set wallpaper and lock screen
feh --bg-fill ~/Nextcloud/Pictures/Wallpapers/mke_cityhall_reflect.jpg
xss-lock -- i3lock-fancy -p -- scrot -z &

# load cursor theme
xsetroot -cursor_name left_ptr

# set monitors and desktops
bspc monitor HDMI-0 -d I II III IV
bspc monitor DVI-D-0 -d V VI VII VIII
bspc monitor DP-5 -d IX X

# configuration
bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.66
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam desktop=^4

# starup programs
sxhkd &
tint2 &
mate-volume-control-status-icon &
nm-applet &
nextcloud &
wmname LG3D & # fix android studio
steam &
gtk-launch brave-adpgfoaiaohhedbfjfajiaeniofgjlfk-Default.desktop && sleep 1 && bspc node -d '^9' & # telegram chrome app
